CREATE SCHEMA IF NOT EXISTS retail_sales;

CREATE TABLE IF NOT EXISTS retail_sales.dim_product (
    product_id INTEGER PRIMARY KEY,
    product_position VARCHAR(50) NOT NULL,
    promotion BOOLEAN NOT NULL,
    product_category VARCHAR(50) NOT NULL,
    seasonal BOOLEAN NOT NULL,
    brand VARCHAR(100) NOT NULL,
    url TEXT NOT NULL,
    product_name VARCHAR(255),
    description TEXT,
    product_price NUMERIC(10, 2) NOT NULL,
    currency CHAR(3) NOT NULL,
    terms VARCHAR(100) NOT NULL,
    section VARCHAR(50) NOT NULL,
    season VARCHAR(50) NOT NULL,
    material VARCHAR(100) NOT NULL,
    origin VARCHAR(100) NOT NULL,
    CONSTRAINT dim_product_product_id_positive CHECK (product_id > 0),
    CONSTRAINT dim_product_price_positive CHECK (product_price > 0),
    CONSTRAINT dim_product_currency_format CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE TABLE IF NOT EXISTS retail_sales.dim_city (
    city_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT dim_city_name_not_blank CHECK (BTRIM(city_name) <> '')
);

CREATE TABLE IF NOT EXISTS retail_sales.dim_date (
    date_id DATE PRIMARY KEY,
    calendar_year SMALLINT NOT NULL,
    calendar_quarter SMALLINT NOT NULL,
    month_number SMALLINT NOT NULL,
    month_name VARCHAR(20) NOT NULL,
    day_of_month SMALLINT NOT NULL,
    day_of_week_number SMALLINT NOT NULL,
    day_of_week_name VARCHAR(20) NOT NULL,
    is_weekend BOOLEAN NOT NULL,
    CONSTRAINT dim_date_quarter_range CHECK (calendar_quarter BETWEEN 1 AND 4),
    CONSTRAINT dim_date_month_range CHECK (month_number BETWEEN 1 AND 12),
    CONSTRAINT dim_date_day_range CHECK (day_of_month BETWEEN 1 AND 31),
    CONSTRAINT dim_date_weekday_range CHECK (day_of_week_number BETWEEN 1 AND 7)
);

CREATE TABLE IF NOT EXISTS retail_sales.fact_sales (
    source_record_number BIGINT PRIMARY KEY,
    product_id INTEGER NOT NULL,
    city_id SMALLINT NOT NULL,
    date_id DATE NOT NULL,
    sold_at TIMESTAMPTZ NOT NULL,
    pieces_sold INTEGER NOT NULL,
    CONSTRAINT fact_sales_source_record_positive CHECK (source_record_number > 0),
    CONSTRAINT fact_sales_pieces_positive CHECK (pieces_sold > 0),
    CONSTRAINT fact_sales_utc_date_matches_timestamp
        CHECK (date_id = (sold_at AT TIME ZONE 'UTC')::DATE),
    CONSTRAINT fact_sales_product_fk
        FOREIGN KEY (product_id) REFERENCES retail_sales.dim_product (product_id),
    CONSTRAINT fact_sales_city_fk
        FOREIGN KEY (city_id) REFERENCES retail_sales.dim_city (city_id),
    CONSTRAINT fact_sales_date_fk
        FOREIGN KEY (date_id) REFERENCES retail_sales.dim_date (date_id)
);

CREATE TABLE IF NOT EXISTS retail_sales.product_city_discount (
    product_id INTEGER NOT NULL,
    city_id SMALLINT NOT NULL,
    discount_rate NUMERIC(5, 4) NOT NULL,
    CONSTRAINT product_city_discount_pk PRIMARY KEY (product_id, city_id),
    CONSTRAINT product_city_discount_rate_range CHECK (discount_rate BETWEEN 0 AND 1),
    CONSTRAINT product_city_discount_product_fk
        FOREIGN KEY (product_id) REFERENCES retail_sales.dim_product (product_id),
    CONSTRAINT product_city_discount_city_fk
        FOREIGN KEY (city_id) REFERENCES retail_sales.dim_city (city_id)
);

CREATE INDEX IF NOT EXISTS fact_sales_product_id_idx
    ON retail_sales.fact_sales (product_id);

CREATE INDEX IF NOT EXISTS fact_sales_city_id_idx
    ON retail_sales.fact_sales (city_id);

CREATE INDEX IF NOT EXISTS fact_sales_date_id_idx
    ON retail_sales.fact_sales (date_id);

CREATE INDEX IF NOT EXISTS fact_sales_product_city_idx
    ON retail_sales.fact_sales (product_id, city_id);

CREATE INDEX IF NOT EXISTS product_city_discount_city_id_idx
    ON retail_sales.product_city_discount (city_id);
